/* help.c -- AIS usage text.
 * usage_short() for a bare invocation and -h; usage_long() for --help.
 * Compiled into the binary (no runtime file dependency). */
#include "help.h"

void usage_short(FILE *out)
{
    fputs(
"usage: ais [-f DIR] [-o] KEY...     get records under ALL keys (default; -o = ANY)\n"
"       ais -v VALUE [KEY...]        save VALUE under keys  (repeat -v = multi-link;\n"
"                                    -v - reads stdin; keys optional)\n"
"       ais -i [KEY...]              interactive: ask keys per piped line\n"
"       ais --find TEXT              search: values that contain TEXT\n"
"       ais --doc [KEY...] < FILE    save stdin as a document (a blob file)\n"
"       ais --add ID -v VALUE | --update ID KEY... | --del ID | --del-key KEY\n"
"       ais --timeline [N]           recent records by date (newest first)\n"
"       ais --tags                   every key with its record count (busiest first)\n"
"       ais --dump | --keys | --stats | --compact | --init | --import\n"
"       ais --import-interactively   like --import, but pick each record (y/N)\n"
"       ais --switch [NAME]          switch the current index (-c NAME [DIR] = create)\n"
"       ais --indexes                list named indexes (* = current, 'home' = ~/.ais)\n"
"       ais --serve [PORT]           local web GUI\n"
"       ais --project [KEY]          show / set / clear ('') the default project\n"
"       ais --where                  print the resolved index directory\n"
"\n"
"  bare words are ALWAYS keys; -v marks a value; -k forces a key that looks like a flag\n"
"  -f DIR index dir   -o OR   -p KEY per-call project   -y yes   -d debug\n"
"  run 'ais --help' for examples\n",
        out);
}

void usage_long(FILE *out)
{
    fputs(
"ais: associative index. Save things under keys, get them back by keys.\n"
"\n"
"The rule: a bare word is always a KEY (get is the default). A value to\n"
"save is marked with -v. A command is a --word. So no tag is ever shadowed:\n"
"'ais doc' gets the tag \"doc\"; 'ais --doc' is the command.\n"
"\n"
"GET (default)\n"
"  ais [-o] KEY...                records under ALL keys (-o = ANY)\n"
"\n"
"SAVE (-v marks the value; bare args and -k are keys; keys are optional)\n"
"  ais -v VALUE KEY...            file VALUE under one or more keys\n"
"  ais -v A -v B KEY...           two values -> one multi-link record\n"
"  ais -v VALUE                   keyless (or under the default project); find/tag later\n"
"  ais -v - KEY...                file each stdin line (a value) under these keys\n"
"  ais -i KEY...                  interactive: stdin lines are values, prompts for keys\n"
"  ais -k KEY ...                 force a key that begins with '-'\n"
"\n"
"COMMANDS (--word; operands are bare args, values via -v)\n"
"  ais --find TEXT                records whose value contains TEXT\n"
"  ais --doc KEY... < FILE        save a multi-line document as a blob file\n"
"  ais --add ID -v VALUE          attach another link to record ID\n"
"  ais --update ID KEY...         edit record ID's keys: KEY attaches, -KEY detaches\n"
"                                 (the id is the 'id|value' from get; -KEY needs --)\n"
"  ais --del ID                   delete record ID\n"
"  ais --del-key KEY              delete every record filed under KEY\n"
"  ais --dump | --keys | --stats  print records / list keys / counts\n"
"  ais --timeline [N]             the N most recent records, newest first (default 500;\n"
"                                 a GUI pages through older ones on demand)\n"
"  ais --tags                     every key with how many records use it (busiest first)\n"
"  ais --compact                  reclaim space from deleted records\n"
"  ais --init                     create a local .ais index here (git-style)\n"
"  ais --import < FILE            add 'keys|value' lines (the inverse of --dump)\n"
"  ais --import-interactively     like --import, but confirm each record [y/N]\n"
"                                 (default N); review each before it is stored\n"
"  ais --where                    print the resolved index directory\n"
"  ais --serve [PORT]             local web GUI (default port 8765)\n"
"  ais --project [KEY]            show / set / clear ('') the default project key\n"
"  ais --switch [NAME]            switch the current index; no arg shows it,\n"
"                                 -c NAME [DIR] creates a new index and switches\n"
"  ais --indexes                  list named indexes (* on current; 'home' = ~/.ais)\n"
"  ais --forget NAME              drop a name from the registry (its data dir is kept)\n"
"  ais --default [PATH]           DEPRECATED: the old single default (use --switch)\n"
"\n"
"EXAMPLES\n"
"  # tag a photo (or any path) under several keys\n"
"  ais -v ~/photos/IMG_3920.jpg italy venice 2023\n"
"\n"
"  # or pipe a filtered list in, tagging them all\n"
"  find ~/photos -name '*.jpg' | ais -v - italy venice 2023\n"
"\n"
"  # the everyday case, just type the keys\n"
"  ais italy venice               # filed under BOTH italy AND venice\n"
"  ais -o venice rome             # under venice OR rome\n"
"\n"
"  ais --find gelato              # search by content, not tags\n"
"  ais -v \"call Marina back\"      # quick keyless capture; tag it later\n"
"\n"
"OPTIONS\n"
"  -f, --index DIR   index directory (else: see INDEX LOCATION below)\n"
"  -o, --or          match ANY key (union) instead of all (intersection)\n"
"  -v, --value VAL   a value to save (repeatable; -v - reads stdin)\n"
"  -k, --key KEY     an explicit key (for a key that looks like a flag)\n"
"  -p KEY            default project prepended to this save ('' = none;\n"
"                    persistent via 'ais --project KEY')\n"
"  -i, --interactive save interactively: stdin lines are values, prompts for keys\n"
"  -y, --yes         assume yes for --del / --del-key / --compact (no prompt)\n"
"  -h                short help;  --help  this full help\n"
"  --version         print version and exit\n"
"\n"
"INDEX LOCATION (when -f is not given; no env vars -- -f is the only override)\n"
"  1. the nearest .ais/ at or above the current directory (like git)\n"
"  2. the saved default in ~/.ais/config, if set ('ais --default PATH')\n"
"  3. else ~/.ais, created on first use.  'ais --init' starts a local .ais here.\n"
"\n"
"Re-storing the same value changes nothing (idempotent). The index is plain\n"
"text in that directory; read, grep, or repair it by hand.\n",
        out);
}
