@echo off
REM
REM Wrapper script for starting of embedded server (currently Jetty).
REM If you want to run the server under Tomcat or JBoss, use war
REM generated by: ant deploy
REM


set CP=%CP%.
set CP=%CP%;classes
set CP=%CP%;www\WEB-INF\lib\ais.jar
set CP=%CP%;www\WEB-INF\lib\log4j.jar
set CP=%CP%;www\WEB-INF\lib\lucene-core-2.4.1.jar
set CP=%CP%;lib\org.mortbay.jetty.jar
set CP=%CP%;lib\commons-logging.jar
set CP=%CP%;lib\servlet-api.jar
REM set CP=%CP%;lib\jetty-6.1.19.jar
REM set CP=%CP%;lib\jetty-util-6.1.19.jar
set CP=%CP%;lib\servlet-api.jar


java -classpath "%CP%";"%CLASSPATH%" org.is.EmbeddedServer %1 %2 %3 %4 %5 %6 %7 %8 %9

pause
