#
# $Id: system.properties,v 1.3 2009/08/12 21:07:59 vgavrilov Exp $
#

#
# Path to the index (index will be created automatically - 
# if not exists. The following 2 indices are for web
# interface (where we have 2 repositories).  
# In command-line interface - any directory or path may be passed
# with -i (--index) flag
#
# Even for windows paths - use forward slashes ('/')
#
index.path.public=INDEX
index.path.private=INDEX_PRIVATE

#
# Jetty section
#
server.embedded.port=8080

# WWW root
DocumentRoot=./www

#
# Directory under DocumentRoot which is public and files under which should 
# be accessible through the browser - in case of auto-indexing.
# This directory should be a simbolic link to the real directory with the same 
# name. For example - let we publish /mnt/disk1.
# In this case we create: ln -s /mnt/disk1 ./ais/www/disk1 
# and run auto-indexing passing the same directory: $./ais --dir=/mnt/disk1
#
# This will work only under Unixes. However under windows files also  
# can be accessible through the Explorer - if we'll map a drive to a 
# directory and will auto-index the whole drive:
# C:\ais>ais --dir=M:\
#
#
repository.path=ISROOT

#
# remote index - when used
#
index.remote.url=http://localhost:8080/ais/main
